# Config for https://github.com/apps/release-drafter
template: |
  ## TODO: Added/Removed/Fixed/Changed

  $CHANGES

  ## Upgrading

  To upgrade, update your `pipeline.yml` files:

  ```diff
  steps:
    - command: simple-command
      plugins:
  -     example-library#$PREVIOUS_TAG: ~
  +     example-library#TODO: ~
  ```
